### PR TITLE
[MelangeResource] Create a MelangeResource per adapted resource

### PR DESCRIPTION
**Pull request by ebousse**
As discussed recently, this is an attempt at creating one MelangeResource per adapted resource. This avoids having duplicate adapted resources, if accessed one as a dependency of a MelangeResource, and later as a MelangeResource of its own.

### CODE REVIEW

**Comment by ebousse** [comment]
But I hope that it does not break too many things! Also it's maybe not very pretty.

**Comment by fcoulon** [comment]
Seems a good idea to me. Do you have some test case/idea for the test suite?

I wrote this some time ago to test cross references (but not sure it still working):
https://github.com/diverse-project/melange/blob/master/tests/fr.inria.diverse.melange.tests/src/main/java/fr/inria/diverse/melange/tests/MultipleResourceTest.xtend

**Comment by ebousse** [comment]
These tests offer a good start I think.

If we have a model1 depending on model2, one test could be:
1. Load model1 as a `MelangeResource`
2. Check that model2 was loaded as a `MelangeResources` as well
3. Load model2 as a `MelangeResource`
4. Check that it re-used the corresponding `MelangeResource` that was created in step 1, instead of creating a new one

However note that I think that my PR will not make it possible yet to first load model2, then model1, because my code only passes the objects mapping of the `ModelCopier` when automatically loading each dependency, but not when reusing a pre-loaded dependency.

**Comment by ebousse** [comment]
Anyone wanting to have a second look? :) Is it required that I write tests as well to have this PR merged?

**Comment by tdegueul** [comment]
This one is a little tricky so I'll have a look in the coming days.

**Comment by tdegueul** [comment]
Merge & Pray.

**Comment by ebousse** [comment]
Erm, I was in the process of testing my merge commit, and was planning to add a comment here only once this was done :). 

I'll let you know what the results are... hopefully good!

**Comment by ebousse** [comment]
Looks like this broke some stuff, according to the Melange test suite: https://ci.inria.fr/k3al/job/melange-master/682/testReport/

**Comment by ebousse** [comment]
(Working on it, new PR coming soon)

**Pull request merged**
