### PR TITLE
Add use of a transaction when the Language has an editing domain

### PR DESCRIPTION
**Pull request by ebousse**
In some situations I have a hard time to identify, I have transaction errors when the Melange builder is called.

It seems to be caused by modifications made to the Language resource (`res?.contents?.add(syntax)`), which in some cases must be in a `ResourceSet` with an editing domain for some reason.

To make the error disappear, I have written the following patch... but I would understand you don't use it since the problem is rather unclear. In fact this pull request is mostly there to inform you of the weird problem.

### CODE REVIEW

**Comment by ebousse** [comment]
ah, conflicts, sorry, I must have forgotten to pull
EDIT: solved

**Comment by tdegueul** [comment]
Seems like I already commented `// FIXME: I don't understand what's going on here` on this piece of code. I don't remember why we had to use this "RootPackage" hack. Do we still need this @fcoulon?

**Comment by fcoulon** [comment]
I introduced the Resource in ff8d8341c1a95a45d426f4d61131d284a0d74e50

If we remove r.contents.add(syntax) the outline break, we can see the content of the packages of the syntax anymore :(

**Comment by tdegueul** [comment]
I remember now, but it still sounds weird :)

We can merge this until we get rid of this hack. Thanks Erwan!

**Pull request merged**
